### ISSUE TITLE
AttributeError: 'Connection' object has no attribute 'errno'

### ISSUE THREAD

**Issue by haveamission** [django-query-profiler/django-query-profiler#19]
I am getting this error after installation.

It seems to be based on this line:

`"ENGINE": "django_query_profiler.django.db.backends.mysql",`

When I remove the `django_query_profiler`, no issue, but when it is in the engine string, it always throws:

```
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django_query_profiler/django/db/backends/mysql/base.py", line 12, in db_row_count
    return cursor.rowcount if not cursor.connection.errno() else -1
AttributeError: 'Connection' object has no attribute 'errno'
```

**Comment by yashmaheshwari** [comment]
What is the mysql driver you are using ? Is it mysqlclient  or MySQL Connector/Python 
See [here](https://docs.djangoproject.com/en/3.2/ref/databases/#mysql-db-api-drivers)

This is what we are doing for mysql

```
    @staticmethod
    def db_row_count(cursor) -> Optional[int]:
        return cursor.rowcount if not cursor.connection.errno() else -1
```

If it is related to the mysql driver, maybe we can check with a `hasattr` check first

**Comment by haveamission** [comment]
I am using PyMySQL:

https://pypi.org/project/PyMySQL/

**Comment by haveamission** [comment]
This seems to fix it on my end:

```
    @staticmethod
    def db_row_count(cursor) -> Optional[int]:
        if not hasattr(cursor.connection, "errno"):
            return -1
        return cursor.rowcount if not cursor.connection.errno() else -1
```

**Comment by yashmaheshwari** [comment]
Ohh, okay.  I believe from the code you have, it would always return -1 -- because it would always go to the if block.

Should it be this:

```
 @staticmethod
    def db_row_count(cursor) -> Optional[int]:
        return cursor.rowcount if not hasattr(cursor.connection, "errno") else -1 # See Issues#19
```

From the [documentation of PyMySQL on rowcount](https://www.python.org/dev/peps/pep-0249/#rowcount), cursor.rowcount returns -1 if there is some exception - which is what we want to return in case of exception from this function -- so we should be good.

**Comment by haveamission** [comment]
When I try your fix, I get this error:

```
  File "/usr/local/lib/python3.7/site-packages/django_query_profiler/django/db/backends/mysql/base.py", line 12, in db_row_count
    if getattr(cursor.connection, "errno", None):  # See Issues#19;  Mysql has multiple drivers
AttributeError: 'Connection' object has no attribute 'errno'
```

**Comment by yashmaheshwari** [comment]
Ohh, maybe it is because the connection class in pyMySQL might have `__getattr__` defined in a way that it throws exception.  I am not sure if that is the case, but a similar example is discussed on [stackoverflow here](https://stackoverflow.com/questions/24794696/why-is-getattr-throwing-an-exception-when-an-attribute-doesnt-exist)

I have pushed a new commit with try except rather than getattr approach;  I think this should work.
Can you try one more time ?  I would merge this PR and release a new version after your confirmation.

**Comment by yashmaheshwari** [comment]
Can you try the new version (0.7);  It should be fixed now

**Comment by django-query-profiler** [comment]
Closing this issue.
